# Generated by Django 4.1.2 on 2022-10-10 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsUTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_campaign', models.CharField(max_length=100, verbose_name='utm_campaign')),
                ('utm_source', models.TextField(max_length=250, verbose_name='utm_source')),
                ('utm_medium', models.CharField(max_length=100, verbose_name='utm_medium')),
                ('utm_term', models.CharField(blank=True, default='Not specified', max_length=100, verbose_name='utm_term')),
                ('utm_content', models.CharField(blank=True, default='Not specified', max_length=100, verbose_name='utm_content')),
            ],
        ),
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, unique=True, verbose_name='user_name')),
            ],
        ),
        migrations.CreateModel(
            name='UTMTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.IntegerField(default=1, verbose_name='event')),
                ('date_time', models.DateTimeField(verbose_name='date_time')),
                ('utm_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utm.projectsutm')),
            ],
        ),
        migrations.CreateModel(
            name='UserProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30, verbose_name='project_name')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utm.username')),
            ],
        ),
        migrations.AddField(
            model_name='projectsutm',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utm.userprojects'),
        ),
    ]
