# Generated by Django 4.1.2 on 2022-10-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsutm',
            name='utm_url',
            field=models.URLField(default='url', max_length=700, verbose_name='utm_url'),
        ),
    ]
